[ERROR] [17-09-07 14:07:12,627] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.NullPointerException
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[ERROR] [17-09-07 14:16:55,034] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.NullPointerException
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[ERROR] [17-09-07 14:17:47,480] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.NullPointerException
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[ERROR] [17-09-07 14:19:28,777] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.NullPointerException
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[ERROR] [17-09-07 14:20:33,647] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.NullPointerException
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[ERROR] [17-09-07 14:24:53,527] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.NullPointerException
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[FATAL] [17-09-07 14:28:53,574] [hibernate.connection.DatasourceConnectionProvider] -- (Could not find datasource: java:comp/env/jdbc/forex)
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:307)
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:344)
	at javax.naming.InitialContext.lookup(InitialContext.java:411)
	at org.hibernate.connection.DatasourceConnectionProvider.configure(DatasourceConnectionProvider.java:52)
	at org.hibernate.connection.ConnectionProviderFactory.newConnectionProvider(ConnectionProviderFactory.java:124)
	at org.hibernate.connection.ConnectionProviderFactory.newConnectionProvider(ConnectionProviderFactory.java:56)
	at org.hibernate.cfg.SettingsFactory.createConnectionProvider(SettingsFactory.java:366)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:60)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:1859)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1152)
	at com.talent.exam.dao.HibernateSessionFactory.<clinit>(HibernateSessionFactory.java:32)
	at com.talent.exam.dao.BaseHibernateDAO.getSession(BaseHibernateDAO.java:14)
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[ERROR] [17-09-07 14:28:53,591] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.NullPointerException
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[FATAL] [17-09-07 14:43:14,377] [hibernate.connection.DatasourceConnectionProvider] -- (Could not find datasource: java:comp/env/jdbc/forex)
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:307)
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:344)
	at javax.naming.InitialContext.lookup(InitialContext.java:411)
	at org.hibernate.connection.DatasourceConnectionProvider.configure(DatasourceConnectionProvider.java:52)
	at org.hibernate.connection.ConnectionProviderFactory.newConnectionProvider(ConnectionProviderFactory.java:124)
	at org.hibernate.connection.ConnectionProviderFactory.newConnectionProvider(ConnectionProviderFactory.java:56)
	at org.hibernate.cfg.SettingsFactory.createConnectionProvider(SettingsFactory.java:366)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:60)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:1859)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1152)
	at com.talent.forex.core.HibernateSessionFactory.<clinit>(HibernateSessionFactory.java:19)
	at com.talent.exam.dao.BaseHibernateDAO.getSession(BaseHibernateDAO.java:14)
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[ERROR] [17-09-07 14:43:14,390] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.NullPointerException
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[WARN ] [17-09-07 15:04:01,025] [hibernate.connection.UserSuppliedConnectionProvider] -- (No connection properties specified - the user must supply JDBC connections)
[WARN ] [17-09-07 15:04:01,181] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[ERROR] [17-09-07 15:04:02,212] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.UnsupportedOperationException: The user must supply a JDBC connection
	at org.hibernate.connection.UserSuppliedConnectionProvider.getConnection(UserSuppliedConnectionProvider.java:30)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:315)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:109)
	at org.hibernate.jdbc.AbstractBatcher.prepareStatement(AbstractBatcher.java:93)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:1948)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2405)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:37)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:243)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:269)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:167)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:101)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:186)
	at org.hibernate.event.def.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:33)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:175)
	at org.hibernate.event.def.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:27)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireSave(SessionImpl.java:544)
	at org.hibernate.impl.SessionImpl.save(SessionImpl.java:533)
	at org.hibernate.impl.SessionImpl.save(SessionImpl.java:529)
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[WARN ] [17-09-07 15:06:03,365] [hibernate.connection.UserSuppliedConnectionProvider] -- (No connection properties specified - the user must supply JDBC connections)
[WARN ] [17-09-07 15:06:03,437] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[ERROR] [17-09-07 15:06:04,312] [exam.dao.ExamContentDAO] -- (save failed)
java.lang.UnsupportedOperationException: The user must supply a JDBC connection
	at org.hibernate.connection.UserSuppliedConnectionProvider.getConnection(UserSuppliedConnectionProvider.java:30)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:315)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:109)
	at org.hibernate.jdbc.AbstractBatcher.prepareStatement(AbstractBatcher.java:93)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:1948)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2405)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:37)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:243)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:269)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:167)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:101)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:186)
	at org.hibernate.event.def.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:33)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:175)
	at org.hibernate.event.def.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:27)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireSave(SessionImpl.java:544)
	at org.hibernate.impl.SessionImpl.save(SessionImpl.java:533)
	at org.hibernate.impl.SessionImpl.save(SessionImpl.java:529)
	at com.talent.exam.dao.ExamContentDAO.save(ExamContentDAO.java:23)
	at com.talent.exam.domain.test.test(test.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
[WARN ] [17-09-07 15:14:11,487] [hibernate.connection.UserSuppliedConnectionProvider] -- (No connection properties specified - the user must supply JDBC connections)
[WARN ] [17-09-07 15:14:11,563] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:16:41,459] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:19:01,966] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:26:31,478] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:26:32,341] [hibernate.util.JDBCExceptionReporter] -- (SQL Error: 1054, SQLState: 42S22)
[ERROR] [17-09-07 15:26:32,341] [hibernate.util.JDBCExceptionReporter] -- (Unknown column 'ExamNo' in 'where clause')
[WARN ] [17-09-07 15:27:32,374] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:28:05,807] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:28:43,301] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:28:44,139] [hibernate.util.JDBCExceptionReporter] -- (SQL Error: 1054, SQLState: 42S22)
[ERROR] [17-09-07 15:28:44,139] [hibernate.util.JDBCExceptionReporter] -- (Unknown column 'ExamNo' in 'where clause')
[WARN ] [17-09-07 15:30:22,259] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:48:43,175] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 15:49:38,482] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 16:43:48,649] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 16:55:48,823] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 16:56:28,070] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-07 17:37:42,092] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:11:18,071] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:15:05,929] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:20:57,041] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:22:28,099] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:26:36,483] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:38:31,090] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:41:19,705] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:50:16,475] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:51:06,173] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 11:51:07,039] [hibernate.util.JDBCExceptionReporter] -- (SQL Error: 1062, SQLState: 23000)
[ERROR] [17-09-08 11:51:07,039] [hibernate.util.JDBCExceptionReporter] -- (Duplicate entry '6-1' for key 'exam_NO_STEP')
[WARN ] [17-09-08 11:52:39,925] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 14:18:23,769] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 14:18:24,683] [hibernate.util.JDBCExceptionReporter] -- (SQL Error: 1451, SQLState: 23000)
[ERROR] [17-09-08 14:18:24,683] [hibernate.util.JDBCExceptionReporter] -- (Cannot delete or update a parent row: a foreign key constraint fails (`forex`.`exam_one_click`, CONSTRAINT `exam_one_click_ibfk_1` FOREIGN KEY (`exam_NO`) REFERENCES `exam_content` (`exam_NO`)))
[WARN ] [17-09-08 14:20:17,544] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 14:20:18,427] [hibernate.util.JDBCExceptionReporter] -- (SQL Error: 1451, SQLState: 23000)
[ERROR] [17-09-08 14:20:18,427] [hibernate.util.JDBCExceptionReporter] -- (Cannot delete or update a parent row: a foreign key constraint fails (`forex`.`exam_one_click`, CONSTRAINT `exam_one_click_ibfk_1` FOREIGN KEY (`exam_NO`) REFERENCES `exam_content` (`exam_NO`)))
[WARN ] [17-09-08 14:22:53,892] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 14:23:46,594] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-08 14:23:47,512] [hibernate.util.JDBCExceptionReporter] -- (SQL Error: 1451, SQLState: 23000)
[ERROR] [17-09-08 14:23:47,512] [hibernate.util.JDBCExceptionReporter] -- (Cannot delete or update a parent row: a foreign key constraint fails (`forex`.`exam_one_click`, CONSTRAINT `exam_one_click_ibfk_1` FOREIGN KEY (`exam_NO`) REFERENCES `exam_content` (`exam_NO`)))
[WARN ] [17-09-08 14:41:27,564] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-11 09:41:16,792] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-11 09:42:42,875] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-11 09:48:52,337] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-11 09:50:44,336] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-11 09:54:25,374] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-11 09:55:41,715] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-11 09:59:49,380] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-11 10:02:28,388] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-18 14:17:20,552] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-18 14:20:55,629] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-18 14:23:11,921] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-18 14:30:34,177] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-18 14:39:12,307] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: jar:file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/lib/ehcache-1.1.jar!/ehcache-failsafe.xml)
[WARN ] [17-09-18 14:55:31,960] [ehcache.config.Configurator] -- (No configuration found. Configuring ehcache from ehcache-failsafe.xml found in the classpath: file:/D:/Workspaces/MyEclipse/forex/WebRoot/WEB-INF/classes/ehcache-failsafe.xml)
[WARN ] [17-09-18 15:29:40,197] [hibernate.util.JDBCExceptionReporter] -- (SQL Error: 1146, SQLState: 42S02)
[ERROR] [17-09-18 15:29:40,197] [hibernate.util.JDBCExceptionReporter] -- (Table 'forex.exam_acc_type' doesn't exist)
